---

- hosts: all
  become: yes
  tasks:
  - name: Install Zabbix-Agent
    yum: name=https://repo.zabbix.com/zabbix/6.4/rhel/7/x86_64/zabbix-release-6.4-1.el7.noarch.rpm

  - name: Install Zabbix latest version
    yum: name=zabbix-agent state=latest
    when:
        ansible_os_family == "RedHat"
    notify:
        zabbix-agent system

  - name: Download zabbix repo package
    get_url:
      url: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu20.04_all.deb
      dest: /tmp/zabbix.deb
   - name: Download agent.service debian
     shell: | 
    dpkg -i /tmp/zabbix.deb
    apt update
    when:
      ansible_os_family == "Debian"
    notify:
      zabbix-agent systemd

  - name: Install zabbix-agent on Ubuntu
    apt:
      name: zabbix-agent
      state: latest
    when:
        ansible_os_family == "Debian"
    notify:
        zabbix-agent systemd

  - name: Stop service zabbix-agent
    become: yes
    service:
      name: zabbix-agent
      state: stopped

  - name: Remove zabbix config file
    become: yes
    file:
      path: /etc/zabbix/zabbix_agentd.conf
      state: absent

  - name: Create new zabbix config file from template
    become: yes
    template:
      src: "templates/zabbix_agentd.conf.j2"
      dest: "/etc/zabbix/zabbix_agentd.conf"

  - name: Start service zabbix-agent
    become: yes
    service:
      name: zabbix-agent
      enabled: yes
      state: started

  handlers:
  - name: zabbix-agent system 
    systemd:
      name: zabbix-agent.service
      enabled: yes
      state: started

  - name: zabbix-agent systemd
    systemd:
      name: zabbix-agent.service
      enabled: yes
      state: started