---
- name: Установка софта на CentOS 7
  hosts: centos.my
  become: yes
  vars:
    pg_version: "12"

  tasks:
  - name: Install EPEL repository on CentOS 7
    yum: name=epel-release state=latest

  - name: Install PostgreSQL
    yum: name=https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    notify:
      - reload_his

  - name: Install PostgreSQL 12
    yum: name={{ item }} state=latest
    loop:
      - postgresql12
      - postgresql12-server
    notify:
      - initdb

  - name: Copy package files
    copy:
      src: "/home/yamrsmokey/soft/"
      dest: "/tmp/"
    register: copy_result

  - name: Install packages
    yum:
      name:
        - "/tmp/logstash-8.6.2-x86_64.rpm"
        - "/tmp/elasticsearch-8.6.2-x86_64.rpm"
        - "/tmp/kibana-8.6.2-x86_64.rpm"
        - "/tmp/filebeat-8.6.2-x86_64.rpm"
      state: present

  - name: Start and enable services
    systemd:
      name: "{{ item }}"
      state: started
      enabled: true
    loop:
      - logstash.service
      - elasticsearch.service
      - kibana.service
      - filebeat.service

  handlers:
  - name: reload_his
    systemd: state=reloaded name=postgresql-{{ pg_version }}

  - name: initdb
    command: /usr/pgsql-{{ pg_version }}/bin/postgresql-{{ pg_version }}-setup initdb
    args:
      creates: /var/lib/pgsql/12/data/PG_VERSION

